### ISSUE TITLE
Request: tag 0.1.0 as v0.1.0

### ISSUE THREAD

**Issue by kenshaw** [MichaelS11/go-cql-driver#3]
I noticed that you tagged yesterday `0.1.0`. As a request, would it be possible to tag this release as `v0.1.0`? I believe it should then work properly with Go modules. I'm asking because this driver is being used in [`usql`](https://github.com/xo/usql).

Additionally, it'd be useful if `go.mod` and the related `go.sum` were included.

Appreciate the work you've done on this project! Thanks!

**Comment by MichaelS11** [comment]
Sure thing, changed to v0.1.0.

I have not used go.mod and go.sum yet. Would have to look into it. I am assuming it is not that hard. It is something you can do a PR for?
